version: "3"

services:
  app:
    build: .
    container_name: nest_app
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db:database
    depends_on:
      - db

  db:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes: 
  pgdata:
    driver: local